### ISSUE TITLE
Blog post title on page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#128]
When you look at a blog post there is no title on the page.

**Comment by oleksis** [comment]
Can put a example where the title ? I test the blog post [What is the US Conference City Diversity Metric](https://blackpythondevs.github.io/2023-11-11-what-is-the-us-conference-city-diversity-metric/) and the header have the title from the post

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/a61ac52d-33ac-47a0-a8a7-15ea80f3bc01)

**Comment by kjaymiller** [comment]
> Can put a example where the title ? 

On the page itself this is a fast way to know you're where you're supposed to be in case folks came from somewhere other than the main page.

**Comment by oleksis** [comment]
Like add the `H1` or `#` for the post markdown file
```markdown
# What is the US Conference City Diversity Metric
...
```

**Comment by kjaymiller** [comment]
So the solution is to ensure that the first line of the doc is the same as the title?
I wasn't sure if this was something we would want to add to the template (especially since we include the title in the frontmatter)

**Comment by oleksis** [comment]
Then we set the title from frontmatter in the post template ?
