### ISSUE TITLE
Diversity index post has some copied text

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#129]
Should be removed

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/d6a30fe9-b9f6-40a5-a3fd-304f404dbc61)

**Comment by kjaymiller** [comment]
lol... I just fixed and close this already?

**Comment by oleksis** [comment]
Sorry I will wait more time for the **Assignees** work on the Issue
