### ISSUE TITLE
Add links to the issues to add events and confrerences

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#131]
Someone may know of a conference that we should add. It would be nice to be able to have a link that would kick to the new issue template.

![Example of some text to add to the site](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/d72f727a-066c-4a9f-b6e6-a79313cfadea)

**Comment by oleksis** [comment]
Can share in the comment the Markdown text with the link for add the Conference ?

**Comment by kjaymiller** [comment]
link to add - `Have a Conference to Add - [Submit an Issue](https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/new?assignees=&labels=conference&projects=&template=add_conference.yml&title=%5BCONFERENCE%5D+%3CCONFERENCE+NAME%3E+YYYY)`
