### ISSUE TITLE
Hide `_No Response_` areas

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#136]
The latest add for FlaskCon was is a virtual only event and the website didn't really have a summary so I didn't add one. 

The website took the `_no reponse_` entries and added them directly. We should check for these and fix.

![Screenshot where areas where no response was provided was added directly to the website](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/acecc711-8dcd-4627-a89f-69cd858f0f97)

**Comment by oleksis** [comment]
Related with how we parse the Issue entry. [Read more](https://github.com/BlackPythonDevs/blackpythondevs.github.io/commit/140ddae5cee67f185ef5f88efa89cd5b317d0417#r132348114) about this
