### ISSUE TITLE
Remove Deprecated Repos from Devcontainer

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#137]
We should replace these extensions with the recommended Ruby LSP extension.

![Deprecation message](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/f793bdac-f70e-487b-91dc-a05fff5c0458)

**Comment by oleksis** [comment]
- [An incompatible extension prevents VS Code from connecting](https://code.visualstudio.com/docs/remote/troubleshooting#_an-incompatible-extension-prevents-vs-code-from-connecting)
