### ISSUE TITLE
[BUG] i18n header links default to english even if language is set to `es`

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#17]
# Steps to reproduce

1. Visit website - https://blackpythondevs.github.io
2. change language to `es`
3. Click the `Acera De` link

![Header with markers to internationalization and menu headers](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/ab7bf6c3-5e55-400d-8d8a-0336205f84c8)

The site will revert back to English.

# Steps to complete

The header should change if the language is set. This is likely done in the template somewhere.

# Further Steps

Frontend testing should be enabled to test that links in the header are consistent when the language is set.

**Comment by oleksis** [comment]
The further steps can be solved in the #18
