### ISSUE TITLE
Add testing via playwright on successful build to ensure no frontend issues

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#18]
When the site builds there is always the potential that some link or other problem arises. If we add playwright tests we can ensure that our links are valid and that changes in the future behave as expected.

## To create

Create a github action that installs playwright and runs the playwright tests.

For python you can install and run playwright

```python
python -m pip install playwright pytest-playwright
python -m playwright install --with-deps
python -m pytest
```

**Comment by oleksis** [comment]
See #17 

> Further Steps
> Frontend testing should be enabled to test that links in the header are consistent when the language is set.
