### ISSUE TITLE
Add Support for GitPod

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#200]

**Comment by oleksis** [comment]
- We need the necessary permissions (Organization or Repository) to use Gitpod app

![Gitpod-App](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/d733ce73-0c3e-4b3c-a781-dc23b2a5750b)

**Comment by oleksis** [comment]
- BPDev website on Gitpod

![Gitpod-BPDevs-website](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/e6f5b150-f714-4874-b3e3-048da0933266)
