### ISSUE TITLE
Change Header to Black Python Devs

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#205]
Currently it reads BPDevs while we're waiting on an official logo some of our partners wants to include us on the website.

If we can just have the website have "Black Python Devs" instead of "BPDevs" we can just have them grab a clip from there.

**Comment by kjaymiller** [comment]
![Black Python Devs Logo](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/f93d00be-03e4-48ba-8be3-1d1724cb8ae1)

**Comment by kjaymiller** [comment]
I've attached an SVG. I think it may need to be cleaned up a bit

**Comment by kjaymiller** [comment]
![Black Python Devs](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/8632637/0396135a-f4b8-489a-a241-70ef3b37b055)

**Comment by oleksis** [comment]
I testing the logo in a dark theme and look darker, but for starting good job 👏🏾

**Comment by oleksis** [comment]
`Black Python Devs` on dark themes

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/5420b3cb-aec5-4e92-b737-37a1d49dc681)

**Comment by kjaymiller** [comment]
Do you know if there is a way to have two images and alternate them with it being an svg can we apply a stroke to it in dark-mode to change the color?

**Comment by oleksis** [comment]
I see a workaround similar idea and solution to the issue for the Textualize/rich logo: https://github.com/Textualize/rich/blob/master/assets/logo.svg
