### ISSUE TITLE
[Event] PyCon US Social and Cultural Museum Visit

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#211]
### Event Name

PyCon US Social and Cultural Museum Visit

### URL

https://awaacc.org/

### Event Date

16 May - 16 May 2024

### Event start time & end time

1:00PM-3:00PM GMT-5

### Event Type

physical

### Event Location

980 Liberty Ave, Pittsburgh, PA 15222, United States

### Summary

Join us for a visit to the August Wilson African American Cultural Center. Named after the celebrated playwright, this center is a hub of artistic and cultural expression, showcasing the rich heritage of Black Americans in Pittsburgh. From compelling art exhibits to vibrant performances, it offers a unique glimpse into the city's history and the contributions of its African American community.The August Wilson Center is a window into the soul and spirit of Pittsburgh's diverse culture.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimOsahenru** [comment]
Hello @kjaymiller, if the event has already taken place, I think we should close this issue as well.
