### ISSUE TITLE
[Event] Games and Fun at Barcadia

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#212]
### Event Name

Games and Fun at Barcadia

### URL

https://www.barcadiapgh.com/

### Event Date

17 May 2024

### Event start time & end time

8:00pm-10:00pm GMT-5

### Event Type

physical

### Event Location

24 Market Square, Pittsburgh, PA 15222, United States

### Summary

Come together for a fun-filled community night at Barcadia Arcade Bar in Pittsburgh! It's a great opportunity for everyone in our close-knit community to catch up and enjoy a relaxed evening playing classic arcade games. Share laughs, challenge friends to your favorite retro games, and enjoy a selection of drinks in a friendly atmosphere. This gathering at Barcadia is all about strengthening community bonds and creating new memories.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimOsahenru** [comment]
Hello @kjaymiller if this is a past event can we please close this. Thanks
