### ISSUE TITLE
Add default of English to languages on all pages

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#215]
When a user looks at a page with not translation, it should return the English version by default.

To Replicate

Go to the conferences page and change the language to Huasa... 

Currently Behavior:
A 404 is returned

Expected Behavior:
Returns the english text

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller tried replicating the issue but it was returning the English text seems it's been fixed
