### ISSUE TITLE
Update content of About Us page for Swahili

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#223]
The about us page doesn't have the leadership section on it.

Also please note that there is an issues in the mission text that needs to be corrected. I'll work on making this change ASAP. Please wait until it is finished.

- [x] #224

cc: @kazz54

**Comment by kazz54** [comment]
Got it, currently working on translating the missing stuff on the home page and fixing the broken URL

**Comment by oleksis** [comment]
@kazz54 Take as reference the Translation for the [articles in Spanish](https://github.com/BlackPythonDevs/blackpythondevs.github.io/tree/gh-pages/_articles/es)

**Comment by kazz54** [comment]
Yes I used that as reference you can merge the pull request
