### ISSUE TITLE
Add icon for buttondown.email's icon page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#238]
I would also suggest having an icon in the future that also links out to buttondowns email newsletter page.

_Originally posted by @kjaymiller in https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/237#issuecomment-1919420808_

**Comment by zablon-oigo** [comment]
Hello @kjaymiller,  I'm interested in addressing this issue, but I need more clarity. Could you please specify whether the task involves replacing a link with an icon or determining the placement of the icon within the form?

![Capture](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/143833326/c7d2df69-b485-4f92-9d7f-dc8cc755bf14)

**Comment by kjaymiller** [comment]
Happy to have you work on this.

The answer is neither. 

We were talking about adding an email icon in the footer of the site but also on the community page so folks know that is another option to be a part of the community.

**Comment by kjaymiller** [comment]
@zablon-oigo - If you want to work on it still I'm happy to assign it to you.

please confirm

**Comment by zablon-oigo** [comment]
> @zablon-oigo - If you want to work on it still I'm happy to assign it to you.
> 
> please confirm

Yeah, sure! I can tackle it
