### ISSUE TITLE
Update `Blog` page to show all posts or a paginated version.

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#240]
Based on conversations with @oleksis, we have an issue with trying to paginate the `blog.html` page.

I'm offering a suggestion.

For `index.html` we can include a `latest-posts.html` fragment which is our current `posts.html` fragment

For `blog.html` we include an `all-posts.html` fragment that doesn't have the `limit` flag.
We can also work to reduce the footprint of the posts to keep the `blog.html` page from getting bloated.

When we figure out pagination we can figure that out later.

**Comment by zablon-oigo** [comment]
Hello @kjaymiller,
Regarding the task, do we plan to rename {%- include posts.html -%} to {%- include latest-posts.html -%}, and subsequently create a new template named all-posts.html to list all blogs?
 Also, do you think we should make sure that the latest posts are rendered first?  then the older one follows...

**Comment by kjaymiller** [comment]
> Regarding the task, do we plan to rename {%- include posts.html -%} to {%- include latest-posts.html -%}, and subsequently create a new template named all-posts.html to list all blogs?

I think this is a good solution. CC: @oleksis what do you think on this naming.

> Also, do you think we should make sure that the latest posts are rendered first? then the older one follows...

I believe the current implementation of posts.html is setup to render the latests pages first. If I recall you should copy that implemtation and remove the limit.

**Comment by oleksis** [comment]
Any idea or solution to implement is great. The feature to keep is the navigation (sitemap) in different languages (I18N) in the site.
Any __Pull Request__ is welcome.

**Comment by kjaymiller** [comment]
This was completed
