### ISSUE TITLE
[CONFERENCE] DjangoCon US 2024

### ISSUE THREAD

**Issue by tim-schilling** [BlackPythonDevs/blackpythondevs.github.io#262]
### Conference Name

DjangoCon US 2024

### URL

https://2024.djangocon.us/

### Conference Dates

22 - 27 Sep 2024

### Conference Type

both

### Conference Location

Durham, North Carolina, United States

### Summary

DjangoCon US 2024 has been announced! Join us for five days of inspiration, education, and networking opportunities centering around the Django web framework.

The conference will have tutorials on Sunday, September 22nd, talks from Monday, September 23rd through Wednesday, September 25th, and sprints on Thursday and Friday, September 26th and 27th, 2024.

We have a [Call for Proposals open](https://2024.djangocon.us/speaking/) until April 24, for anyone is interested in speaking at the conference.

We also have applications open for [opportunity grants](https://2024.djangocon.us/opportunity-grants/) until April 24, in case anyone is interested in attending but needs financial assistance.

### Speaking

- Felipe De Morais - Building Your First API with Django and Django Rest Framework
- Harmony Elendu - Project Management in Open Source
- Samweli Mwakisambwe - Open-source Python tools to visualize and analyse geospatial data
- Ron Maravanyika - Unlocking Performance: Benchmarking and profiling Django for Maximum Efficiency
- Johanan Oppong Amoateng - Empowering Tertiary Students: Introducing PyClubs for Enhanced Python Skills and Community Engagement
- Eva Nanyonga - Only reliable Data: Protecting Database Integrity
- Richard Ackon - Understanding Database Connection Management in Django

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kjaymiller** [comment]
Thanks for getting this added!

**Comment by tim-schilling** [comment]
Whoops. I meant Carolina not Caroline.

**Comment by tim-schilling** [comment]
I also fixed the dates.

**Comment by kjaymiller** [comment]
added talks to information

**Comment by tim-schilling** [comment]
:partying_face: Thank you for the talks, participation and community!
