### ISSUE TITLE
remove unused pico attributes

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#277]
picoss is designed to be extremely small and lightwight. The color profiles file (pico.colors.min.css) is about the same size as the primary (pico.min.css) and the recommendation from pico is to remove color profiles that are not used to reduce the size.

It would be good to:

remove any unused colors in `pico.colors.min.css`
add a note about pico and pico's color section in contributing.md

**Comment by cmm25** [comment]
Kindly assign me this issue

**Comment by kjaymiller** [comment]
Thank you for taking this on @cmm25 . 

[MINOR UPDATE]:

> add a note about pico and pico's color section in contributing.md

This should go into `maintainers.md`

**Comment by cmm25** [comment]
check pr #473
