### ISSUE TITLE
Add CFP Link and Deadline to Conference Template

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#279]
This is so that we can give folks a quick link to the CFP.

Currently when someone creates an issue there is no section for the cfp link and the cfp deadline. We could help conferences that we hope to sponsor by giving them another place to promote their CFP.

#### To Fix

We need to add lines to the GitHub Form so that it will also include the CFP Link and CFP Deadline.

We also need to add the check for a valid url scheme as defined in #338

**Comment by oleksis** [comment]
Where is the CFP link and deadline to Conference template?

**Comment by kjaymiller** [comment]
Currently our form doesn't have fields for the CFP Link and Deadline. I would like to add them to the page so that we can make sure that folks can quickly submit their CFPs

**Comment by Brijeshthummar02** [comment]
@kjaymiller can you show me the path where to add it.

**Comment by kjaymiller** [comment]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/.github/ISSUE_TEMPLATE/add_conference.yml

**Comment by Brijeshthummar02** [comment]
I placed the CFP Link and CFP Deadline fields after the existing fields for conference_name and conference_date. will it be fine?
