### ISSUE TITLE
Add link to github repo on website

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#29]

**Comment by mannyanebi** [comment]
I'd like to close this issue. I would like to know what page or on which section should the github repo link be added?

**Comment by oleksis** [comment]
@mannyanebi You can follow the [Jekyll Layout](https://jekyllrb.com/docs/step-by-step/04-layouts/) and [Themes](https://jekyllrb.com/docs/themes/)

One option is update the ["footer"](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/_includes/footer.html) and the ["config.yml"](https://github.com/jekyll/jekyll/blob/8e4ccfc4ff3020633b378ca81e17b8e7adee1a39/lib/site_template/_config.yml#L29-L30) with the GitHub and Discord links

**Comment by mannyanebi** [comment]
Oh nice. I'd check out then. Thanks

**Comment by kjaymiller** [comment]
I definitely think the footer is a good option.

**Comment by oleksis** [comment]
@mannyanebi can pull the PR #63 and send the change to the PR

Just need uncomment the GitHub url for social links in the [`config.yml`](https://github.com/oleksis/blackpythondevs.com/blob/6f31e545c945e25e82b27e2670f3e5c1a373a843/_config.yml#L41-L57)

**Comment by mannyanebi** [comment]
Thanks @oleksis. This helped me alot. I'm taking a crash course on jekyll to learn and understand developing with jekyll.

**Comment by oleksis** [comment]
More [Discussion](https://github.com/BlackPythonDevs/.github/discussions/1#discussioncomment-6898012) about the website stacks
