### ISSUE TITLE
Links on Index are broken

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#3]
If you try the links from the gh-pages site. They all point to 404's this is likely due to a relative link issue.

**Comment by oleksis** [comment]
The links are settings for work from a Root domain like `blackpythondevs.com/about'

You can give a test opening the branch in Codespaces (using devcontainer)

**Comment by kjaymiller** [comment]
I will set the domain and see if that works

**Comment by kjaymiller** [comment]
We renamed the repo to `blackpythondevs.github.io` to enable the root path. We'll work on getting things published. We can work on getting the domains working. But it's good now.
