### ISSUE TITLE
Remove those partnerships that are in Planning

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#310]
Remove mentions of the following from the about page:

- Python Morself
- DjangoCon US 2024 (Under Black Python Devs Opportunity Fund)
- PyData Global Events

**Comment by Kabasitad** [comment]
Hello @kjaymiller, can I work on this issue?

**Comment by kjaymiller** [comment]
@Kabasitad  - apologies. it appears this issue has already been resolved.
