### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections 

### ISSUE THREAD

**Issue by sandramsc** [BlackPythonDevs/blackpythondevs.github.io#313]
### Current Behavior

The contributing guide is a great way to introduce new and existing contributors on how to add their contributions to the projects within an organization. Currently, the CONTRIBUTING.md does not state that:

- there is a first-come-first-serve procedure when it comes to assigning open issues.
- allocated time to update the community on your progress

### Desired Situation

Add/update the following sections within the CONTRIBUTING.md of the [BlackPythonDevs](https://github.com/BlackPythonDevs/blackpythondevs.github.io) projects:
- Issues & Pull Requests --> i.e _Creating an Issue, Working on an issue (get it assigned to you)_
- Reviewing Pull Requests

### Checklist for projects
All the CONTRIBUTING.md's need to be updated using above mentioned desired state.

- [x] [BlackPythonDevs](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/CONTRIBUTING.md)
- [ ] [Streamlit Booth Slider](https://github.com/BlackPythonDevs/streamlit-booth-slider/blob/CPNTRIBUTING.md)

**Comment by kjaymiller** [comment]
I'm looking forward to this contribution!
