### ISSUE TITLE
[Documentation] remove CONTRIBUTING.md

### ISSUE THREAD

**Issue by sandramsc** [BlackPythonDevs/blackpythondevs.github.io#317]
### Current Behavior

Currently the CONTRIBUTING.md needs to be applied to projects manually on each project.

### Desired Situation
To automatically add the CONTRIBUTING.md to all projects it will first be removed from each project and added to [.github](https://www.github.com/BlackPythonDevs/.github).

**Comment by kjaymiller** [comment]
more conversation being had on this here - https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/318#issuecomment-2105782120
