### ISSUE TITLE
Correct Sentences in about story

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#319]
In `about.md`

> That same person was also to speak at PyCon US in 2023. After much push from communities in Africa and Brazil we saw the total number of Black Pythonistas triple in number.

This should be

> That same person was accepted to speak at PyCon US in 2023.
> 
> With much push from community in Africa and Brazil, we saw the total number of Black Attendees in 2023 triple in number. (CONTINUE that paragraph)

**Comment by Nitnalyse** [comment]
@kjaymiller is this closed or still opened
