### ISSUE TITLE
Add Leadership Model Page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#320]
We're trying to balance the amount of content on the pages and I wonder if it would be better to create a leadership page. That gives people the ability to see who our community leaders represent.

My thought on the outline of this.

A dedicated leadership page that start by showcasing our leadership team and our leadership council members names and their location and our allyship advisors and their locations.

## BPD Leadership Team

The BPD Leadership Team is the ultimate responsibility for continued operation of Black Python Devs.

- Jay Miller - Executor
- Velda Kiara - Vice Executor, Events Manager
- Doreen Nangira - Treasurer, Code of Conduct Team Coordinator
- Oleksis Fraga - Technical Manager

## BPD Execution Team

The BPD Execution Team are those carrying out the leadership and execution of our many programs.

- Afi Gbadago - Open Source Project Coordinator
- Nuel - Co-Africa Events Coordinator
- Steve Yonkeu - Co-African Events Sponsorship Coordinator
- Nadir "Q" Abdullahq - US Events Coordinator
- Damilola Oladele - Documentation Team Coordinator
- Ron Maravanyika - Zimbabwe Events Coordinator
- Benedict Kofi - US NYC Leadership Coordinator
- Israel - Nigerian Events Coordinator
- Sandra - New Members Liaison

- TBD - Content Team Coordinator
- TBD - Code of Conduct Team Coordinator

## Meetup Leadership Team

The BPD Meetup Leaders are those responsible for the execution of our local meetups in select areas.

- Nadir "Q" Abdullahq - BPD DMV (DC, Maryland, Virginia)
- Stancy - BPD Ghana
- Jay Miller - BPD Atlanta
- Lazouich Ford - BPD Denver 
- Derek "DA" Arnold - Ohio Liaison 

## BPD Community Leadership Council

Leaders in their own communities. This council consists of several local leaders and provide consult to our BPD Leadership.

- Sarah Abderemane
- Denny Perez
- Dawn Wages
- Abigail Mesrenyame Dogbe
- Brayan Kai
- Chris Achinga
- Aisha Belamo
- Kafui Alardo
- Felipe Quieroz
- Marlene Mhangami
- Monica Oyugi
- Ngazetunge Muheue

## Allyship Council

Respected Experts and allies of the Black Python Devs mission. This group serves an outward role of guidance to our leaders in operating responsibly towards the success of our organization mission.

- Carol Willing
- Jeff Triplett
- Holly Million
- Kojo Idrissa
- Iqbal Abdullah

**Comment by zablon-oigo** [comment]
Hey @kjaymiller 

I was thinking if we create a separate page for leadership, we can add a button on the  **about us**  page that will direct users to the leadership page, or we could have a leaders navigation link. I prefer having it on the   **about us**  page, but me know what you think.

**Comment by kjaymiller** [comment]
I like the idea. go ahead and develop the button

**Comment by kjaymiller** [comment]
@zablon-oigo  - I've updated the issue to contain all of our officers and leaders

**Comment by TimOsahenru** [comment]
@zablon-oigo Please what is the status of this task ?

**Comment by kjaymiller** [comment]
It's been 3 months with no followup. Feel free to take on the task.

**Comment by TimOsahenru** [comment]
@kjaymiller kindly review this PR https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/458. Thanks

**Comment by TimOsahenru** [comment]
@kjaymiller please help close this issue. Thanks
