### ISSUE TITLE
Update CONFERENCES TEMPLATE to Specify the FULL URL

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#346]
in the template we need to make sure that people are including the full URL

https://2024.djangocon.us

and not

~~2024.djangocon.us~~

**Comment by dragid10** [comment]
I'm happy to take this!

**Comment by dragid10** [comment]
@kjaymiller Just to double-check, we're talking about the [conferences issue template?](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/.github/ISSUE_TEMPLATE/add_conference.yml)

**Comment by kjaymiller** [comment]
oh wow it's already in there... Perhaps we can add a comment that it needs to be the FULL URL

**Comment by dragid10** [comment]
Hmm just had a thought:

Something else we could do is append "https" in this  parser? https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/_conferences%2F__main__.py

(At least that's what it looks like is happening)
