### ISSUE TITLE
Improve the Contributing section around testing your changes

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#351]
We mention doing things like running `pre-commit` but we don't really provide the best instructions on how to test (or run precommit) on our code. 

If you are using a codespace this is done automatically but not if you are developing locally.

Another option is to have pre-commit add the changes post-commit

### How to fix

We can provide screenshots and instructions on how to test and lint your code prior to pushing your changes.

**Comment by dragid10** [comment]
I can take this!
