### ISSUE TITLE
check and append to parser

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#353]
Hmm just had a thought:

Something else we could do is append "https" in this  parser? https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/_conferences%2F__main__.py

(At least that's what it looks like is happening)

_Originally posted by @dragid10 in https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/346#issuecomment-2209619501_

**Comment by dragid10** [comment]
I've been busy, but I'm happy to take this!
