### ISSUE TITLE
replace hero image with carousel from latest posts and featured images of them.

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#365]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/98976d9d46e17f78d20a81ef51920c7e13308c28/_layouts/index.html#L6-L8

Newer posts should have a featured image, summary , and title.

We can use those to create a carousel about the latest news.

**Comment by TimOsahenru** [comment]
Hello @kjaymiller please I'm assigning myself to this issue. Thanks

**Comment by TimOsahenru** [comment]
Let me add this here for now https://stackoverflow.com/questions/79104225/how-to-fixing-failing-pytest-in-jekyll-project in case anyone has a fix

**Comment by TimOsahenru** [comment]
**Updates**
https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/544#event
