### ISSUE TITLE
Fix CSS to ensure that `article > li` list style is `None`

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#369]
Update post.

If you look at the page for unorded list > list items are oddly margined. 

![Side-by-side](https://github.com/user-attachments/assets/aaf1bfc0-c2ee-4445-9f9d-3c35ab8f33a4)

Options could be to add left margin or remove the list decoration
![Side by side comparisons](https://github.com/user-attachments/assets/fd0257c5-764c-4cab-a2ba-c9b011ed1566)

**Comment by kjaymiller** [comment]
@VeldaKiara - which do you prefer

**Comment by VeldaKiara** [comment]
Padding left

**Comment by mbvgua** [comment]
I'm happy to work on this issue
