### ISSUE TITLE
[CONFERENCE] Black Python Devs Leadership Summit 2024

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#373]
### Conference Name

Black Python Devs Leadership Summit

### URL

https://blackpythondevs.com/leadership-summit-2024

### Conference Dates

21 - 21 Sep 2024

### Conference Type

both

### Conference Location

Durham, NC, USA

### Summary

We are happy to announce the 2024 Black Python Devs Leadership Summit, held at the Caktus Group in Durham, North Carolina.

This year we’re bringing presentation from folks all over the world to energize and inform our Black Python Devs leaders and distinguished guests.

### Speaking

* [Afi Gbadago](https://www.linkedin.com/in/abigail-afi-gbadago/)
* [Velda Kiara](https://www.linkedin.com/in/veldakiara/)
* [Jay Miller](https://www.linkedin.com/in/kjaymiller)
* [Ron Maravanyika](https://www.linkedin.com/in/ronnzw/)
* [Wesley Faulkner](https://www.linkedin.com/in/wesley83/)
* [Monica Oyugi](https://www.linkedin.com/in/monicaoyugi/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimOsahenru** [comment]
@kjaymiller I'm guessing this is also an automated issue. Please help close it. Thanks

**Comment by kjaymiller** [comment]
Yeah we have an issue that if you close an issue currently it will remove it from the website. 

I'm hoping to get it fixed using another tool that I created a few years back.
