### ISSUE TITLE
Sponsorships and Meetup Receipts

### ISSUE THREAD

**Issue by VeldaKiara** [BlackPythonDevs/blackpythondevs.github.io#380]
We need to make it clear that we need receipts to show how money was spent by the various groups and communities we work with.

**Comment by kjaymiller** [comment]
@VeldaKiara, I think I interpreted this wrong. 

When sponsoring an event or meetup, I don't think we need to be as strict to require the receipts of how the money is used. 

I think this plays into a level of trust that we have with our partners. 

I think it may be too much to ask for financial proof that our money went exactly to the requested use case. It also creates an unnecessary burden on us to then have to maintain all of those records.

**I do think it would be helpful to at least provide a quote from the vendor of the cost of the thing this would be used for. ** That would help in determining our sponsorship decision (example: if a conference wants $2000 from us for catering but the catering will only cost $1000)

When it comes to our meetups I think we do want to keep receipts for reimbursement reasons. But in terms of a sponsorship of a meetup, that follows the same guidance. I would say that we would sponsor to an agreed amount with support from a quote or previous invoice.

**Comment by VeldaKiara** [comment]
Sounds good

**Comment by kjaymiller** [comment]
@VeldaKiara - I think we can close this here and have this information documented by @activus-d and the docs team. I'll copy the information to /blackpythondevs/blackpythondevs
