### ISSUE TITLE
Create Recap of First Black Python Devs in Person Meetup

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#382]

**Comment by TimOsahenru** [comment]
Hello @AfiMaameDufie, just checking in to see if there are any updates on this. Thanks

**Comment by AfiMaameDufie** [comment]
> Hello @AfiMaameDufie, just checking in to see if there are any updates on this. Thanks

Working on this. Thanks for the reminder.
