### ISSUE TITLE
Update path to new prospectus

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#387]
The prospectus was updated and should be updated on the webpage - https://blackpythondevs.com/leadership-summit-2024.

new prospectus path is - https://drive.google.com/file/d/1W-tdNcOiylVB7a3LzUj3oTtfCzWNNIzc/view?usp=sharing

**Comment by jyffarh** [comment]
Hi @kjaymiller , Can you assign this task to me?Thanks
