### ISSUE TITLE
Fix schedule on leadership summit page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#388]
Currently the community track reads

12:00 - 1:00 am: Registration
1:15 - 2:00 am: Keynote Address
2:05 - 2:55: Interactive Session

should read

12:00pm - 1:00pm: Registration
1:15pm - 2:00pm: Keynote Address
2:05pm - 2:55pm: Interactive Session

**Comment by DonBoscoBlaiseA** [comment]
I would like to fix this.
