### ISSUE TITLE
Update README Instructions to include first build steps

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#39]
Add instructions for first time building via codespaces to include:
- Installing the gems (`bundle install`)
- Starting the server
- Opening the URL (from the forwarded port)

If possible include screenshots or terminal output.

**Comment by bilesanmiahmad** [comment]
Great! An issue I can work on

**Comment by oleksis** [comment]
__HINTS__

- The custom Jekyll Devcontainer  image run `bundle install` in the post-create command
- Using the Visual Studio Code [Default Build Task](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/.vscode/tasks.json#L6-L18) <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>B</kbd>

**Comment by oleksis** [comment]
Demo:

[BPDevs-Codespaces.webm](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/650207b8-a477-4f89-88f2-790d03384710)

**Comment by bilesanmiahmad** [comment]
@kjaymiller @oleksis do I create a new PR when I have committed my updates in the forked repo? If so, do I use the same title for this issue in the PR title?

**Comment by oleksis** [comment]
When you fork the repository, create a development branch, make the change or add new features and commit the changes to your fork. 

Then in the GitHub web UI or using the extensions you can send the Pull Request to the [upstream repository]( https://github.com/BlackPythonDevs/blackpythondevs.github.io.git)

## VS Code GitHub Extensions IDs:

- vscode.github
- GitHub.vscode-pull-request-github

You can keep the same title like the Issue and add the comments / descriptions for the issue you try to fix

@bilesanmiahmad

**Comment by bilesanmiahmad** [comment]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/45 @kjaymiller @oleksis
