### ISSUE TITLE
Announce Partnership with O'Reilly 

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#392]
Working Title: "Black Python Devs Meetups and Book Club to Partner with Media Powerhouse O'Reilly Media"

We're proud to announce that Black Python Devs in-person meetups will be partnering with O'Reilly!

- [ ] get quote from O'reilly rep
- [ ] get quote from BPD
- [ ] get quote from meetups organizers

**Comment by VeldaKiara** [comment]
An addition to the partnership, we should add the following to the website to get a free 30-day trial on using the O'reilly Platform.
`<h3 id="2126973"> <a href="https://oreillymedia.pxf.io/c/5713155/2126973/15173"> This is your unique trial link </a> </h3>`

**Comment by kjaymiller** [comment]
Working on this request currently
