### ISSUE TITLE
Add the book club page on the website.

### ISSUE THREAD

**Issue by VeldaKiara** [BlackPythonDevs/blackpythondevs.github.io#396]
The page's title is "Black Python Devs Book Club: A Community of Readers and Learners".

Description:  

The Black Python Devs (BPD) are thrilled to announce the launch of our new Book Club! Founded in March 2024 by our Vice Executor, Velda Kiara, the club was born from the community's growing passion for technical reading and learning.

Our goal is to create a welcoming and supportive space where members can share their love of Python development, discuss industry trends, and dive deeper into technical concepts. By reading and discussing books together, we hope to sharpen our skills, connect with like-minded developers, and contribute to the growth of our community.

The club's founding members, Velda, Sarah Abderemane, Laz, Israel, and Muheue, are dedicated to building a vibrant and engaging community for everyone. Our initiative aligns with BPD's overall mission to increase participation, empower our members, and provide opportunities for professional growth.

Our first completed book for August 2024 is "Boost Your Django DX" by Adam Johnson. This fantastic book offers valuable insights into improving Django development workflows and productivity.

<img width="575" alt="Screenshot 2024-08-25 at 18 44 17" src="https://github.com/user-attachments/assets/8367258c-1d0d-4be0-bc9d-6ece457e652e">

Join us in the [Black Python Devs Book Club (#tech-book-club)  on Discord ](https://discord.gg/XUc3tFqCT3)and discover the power of learning together!

Cover image is also attached here
![BPD Book Club](https://github.com/user-attachments/assets/298250a0-0c01-4e50-84ba-1a170540b923)

**Comment by kjaymiller** [comment]
@VeldaKiara - I think your current description would be great in blackpythondevs/blackpythondevs/programs/book_club.

I do think the description on the site should focus more on things like What books have you covered and what's next and when and where y'all meet.

#### Suggested Updated Description
Description:

The Black Python Devs book club was born from the community's growing passion for technical reading and learning.

Our goal is to create a welcoming and supportive space where members can share their love of Python development, discuss industry trends, and dive deeper into technical concepts. By reading and discussing books together, we hope to sharpen our skills, connect with like-minded developers, and contribute to the growth of our community.

The club's leadership are dedicated to building a vibrant and engaging community for everyone. Our initiative aligns with BPD's overall mission to increase participation, empower our members, and provide opportunities for professional growth.


##### Books Completed (Cards with cover page of the books):
"Boost Your Django DX" by Adam Johnson. This fantastic book offers valuable insights into improving Django development workflows and productivity.

##### Upcoming Books


#### Join Today

Our Book club meets twice in a month on [Discord](https://discord.com/invite/XUc3tFqCT3)


---

#### Implemenetation Details

I would make this a page that inherits from default.

I would also make a `books.json` with `title, author, description, status` keys and the only values for `status` should be `upcoming, reading, read`

**Comment by Selasi3** [comment]
Hello @kjaymiller, I would want to work on this issue.

**Comment by thesumitkrsingh** [comment]
hello i work on these after oct 1 as my first contribution in hacktoberfest assigned me

**Comment by kjaymiller** [comment]
@Selasi3 have you done any work on this.

**Comment by kjaymiller** [comment]
@Selasi3 @thesumitkrsingh please NOTE while we are excited for Hacktoberfest, there are almost (at time of writing) 50 open issues with many being good first issues. We will not hold issues for a later date for folks and as @Selasi3 was assigned the task, we will not remove a person unless there is a clear indication that this project is not being worked on.

**Comment by Selasi3** [comment]
`Yes please I have done work on this issue waiting for reviews`
