### ISSUE TITLE
Nit: Change Velda's title to Vice Executor on the web page

### ISSUE THREAD

**Issue by VeldaKiara** [BlackPythonDevs/blackpythondevs.github.io#398]
<img width="1200" alt="Screenshot 2024-08-27 at 14 39 14" src="https://github.com/user-attachments/assets/38da49f4-ac9e-4568-84db-a71aada84657">

**Comment by mbvgua** [comment]
id like to have this assigned to me as my first issue :smiley:

**Comment by VeldaKiara** [comment]
You have been assigned this issue

**Comment by mbvgua** [comment]
okay. great... currently working on it

**Comment by mbuguadouglas** [comment]
Ayo. Let's goooo!!! :muscle:

**Comment by mbvgua** [comment]
Ayo. My first contribution got merged. Lets gooooo!!! :muscle:
