### ISSUE TITLE
Create a Mermaid Diagram for the `readme.md` or `contributing.md` of the infrastructure in use.

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#402]
It would help folks develop on the system if they understood how the system was setup.

If we create a diagram that includes,

website structure
development structure
how some information is generated

This could live in our documentation to help first time contributors.

**Comment by TimOsahenru** [comment]
This looks exciting. @kjaymiller Please I'm assigning this to myself
