### ISSUE TITLE
Web Page Responsiveness to smaller screens 

### ISSUE THREAD

**Issue by VeldaKiara** [BlackPythonDevs/blackpythondevs.github.io#403]
Bug: When the web page is opened on a small screen, the navigation bar is distorted and though clickable the styling is off.
There is a preference for redesigning it vertically. 

Task: Ensure that the web pages are all responsive despite the size of the screen.

**Comment by mbvgua** [comment]
Hello. looks like I still got to it on time. I'd love to work on this issue.

**Comment by mbvgua** [comment]
Okay. I think this issue should be closed as it is already resolved.
