### ISSUE TITLE
Combine Conferences and Events to one page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#413]
Currently we have the events page with one event (Coffee and Code) and the conferences page that is dynamically built using `_conferences/__main__.py`.

The plan is to combine the two pages to be `events.html`

```mermaid
graph TD
    A[Webpage] --> B[Header]
    B --> C[BPD Events]
    C--> D[Upcomming Conferences]
    D --> E[Footer]
```

**Comment by TimOsahenru** [comment]
@kjaymiller in summary we want our events and conferences to all point here `https://blackpythondevs.com/events/`. Please assign this to me. Thanks

**Comment by kjaymiller** [comment]
yes but you want the two pages to be merged.
