### ISSUE TITLE
Add banner for the leadership summit

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#417]
We need to add a banner for the Leadership Summit on the homepage that way as we start doing a large push on social media, anyone that comes to the website will be able to find the page quickly and easily.

This would be a banner at the top using the `<article></article>` tags at the front.

We can use some text like 

> Join us in Durham, and Online this weekend for the Leadership Summit. Learn More!

**Comment by bboyjamba** [comment]
I'll take this one.
