### ISSUE TITLE
Add Python Software Foundation as a Silver Sponsor

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#422]
On https://blackpythondevs.com/leadership-summit-2024/ - we need to add the PSF as a silver sponsor with their logo on the page

**Comment by Ngazetungue** [comment]
Can you assign this to me

**Comment by Ngazetungue** [comment]
PSF logo added. Added the same time as defna logo. The commit message mistakenly is the same.

**Comment by kjaymiller** [comment]
That's okay. Did you submit a PR for it? I'm not seeing it?

**Comment by Ngazetungue** [comment]
> That's okay. Did you submit a PR for it? I'm not seeing it?

Wait, i was doing everything wrong.
-I cloned the repo
- Create branch /PR locally
- Now i want to push my changes

**Here is the error:** 
remote: Permission to BlackPythonDevs/blackpythondevs.github.io.git denied to Ngazetungue.
fatal: unable to access 'https://github.com/BlackPythonDevs/blackpythondevs.github.io.git/': The requested URL returned error: 403
~/Proj/GitHub/b/blackpythondevs.github.io add-DEFNA-psf-sponsor-423 !1 >

**Comment by Ngazetungue** [comment]
> That's okay. Did you submit a PR for it? I'm not seeing it?

find it here: https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/434

**Comment by TimOsahenru** [comment]
I'm assuming this issue has been resolved, can we close it please. Thanks
