### ISSUE TITLE
Add DEFNA as a bronze sponsor

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#423]
On https://blackpythondevs.com/leadership-summit-2024/ - We need to add DEFNA's Logo as a silver sponsor

**Comment by Ngazetungue** [comment]
Can you assign this to me

**Comment by kjaymiller** [comment]
Go for it. you can probably merge this change with #422

**Comment by Ngazetungue** [comment]
Defa logo added. Added the same time as psf logo. The commit message mistakenly is the same.

**Comment by TimOsahenru** [comment]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/422#issuecomment-2360848377 and this too as well. Thanks
