### ISSUE TITLE
Fix typo in Leadership Summit page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#424]
on /leadership-summit-2024

> This year we’re bringing presentation from folks all over the world to energize and inform our Black Python Devs leaders and guests.

should be 

> This year we’re bringing presentations from folks all over the world to energize and inform our Black Python Devs leaders and guests.

**Comment by daredevil3435** [comment]
I would like to work on this.

**Comment by daredevil3435** [comment]
@kjaymiller  please check my PR  #427

**Comment by kjaymiller** [comment]
> @kjaymiller please check my PR #427

Great work! Feel free to correct some of the other typos we found. Just message that you're working on them so we can assign them to you.

**Comment by daredevil3435** [comment]
Sure!
