### ISSUE TITLE
Add OSSF Scorecard GH Action and badge to README

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#425]
Using this action help us keep track of our OSSF Health and Safety Score of this project.

- https://github.com/ossf/scorecard-action

#### WHY

> to help open source maintainers improve their security best practices and to help open source consumers judge whether their dependencies are safe.

**Comment by CyrilBaah** [comment]
Hi @kjaymiller, would like to work this issue.
