### ISSUE TITLE
Change schedule to show PSF as Silver sponsor

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#426]
on `leadership_summit_2024.md`

> 10:15am - 10:20am: Gold Sponsor Lightning Talk - Python Software Foundation

Should be 

> 10:15am - 10:20am: Silver Sponsor Lightning Talk - Python Software Foundation

**Comment by cmm25** [comment]
Hi Sir. Kindly assign me this issue

**Comment by cmm25** [comment]
@kjaymiller check the pull request #428
