### ISSUE TITLE
[CONFERENCE] Pycon Africa 2024

### ISSUE THREAD

**Issue by Nuel1st** [BlackPythonDevs/blackpythondevs.github.io#429]
### Conference Name

Pycon Africa

### URL

https://africa.pycon.org/

### Conference Dates

24-28 Sep 2024

### Conference Type

in-person

### Conference Location

University of Ghana

### Summary

PyconAfrica has been announced alongside its. The conference would be held 24-28 September, is a five-day international conference for the community. 
PyConAfrica, seek to bring together all amazing folks - or as we call ourselves, Pythonistas - from around the continent and the world to give talks, host tutorials, run hackathons/sprints.

### Speaking

Ugwu Emmanuel - Lightning talk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimOsahenru** [comment]
"Hello @kjaymiller, this is a past event, right? or is there any particular context around why the issue was reopened?"

**Comment by kjaymiller** [comment]
IIRC - I was testing some changes to how the events pages are parsed. For more info - #386
