### ISSUE TITLE
[CONFERENCE] Pycon Uganda

### ISSUE THREAD

**Issue by Nuel1st** [BlackPythonDevs/blackpythondevs.github.io#432]
### Conference Name

PyconUg

### URL

ug.pycon.org

### Conference Start Date

2024-10-09

### Conference End Date

2024-10-13

### Conference Type

in-person

### Conference Location

NWSC International Resource Centre (IREC), Kampala, Uganda

### Summary

The conference is a five-day event, 9-13 October. PyconUganda inherit this tradition of an annual event that brings together python enthusiasts, tech audiences and technology business in uganda and around the world.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimOsahenru** [comment]
Do you mind giving some more context to this issue? Thanks

**Comment by kjaymiller** [comment]
> Do you mind giving some more context to this issue? Thanks

These issues are automated but this is a good point in that the automated issues should have some messaging that no action is needed. @TimOsahenru can you make a new issue to create a comment action that provides some messaging?

**Comment by TimOsahenru** [comment]
Done. Please check it out https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/442. Thanks
