### ISSUE TITLE
Add a social media section to our about page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#436]
~~this will allow us to send people to the website to get links to our social media.~~

~~Yes they are in the header but it would be good to have a standard page link like~~

~~https://blackpythondevs.com/about#social~~

#### [UPDATE]

I'm sorry this actually is a simpler issue which I'm happy for you to address...

We have some new social media locations that need to be change.

We have https://blackpythondevs.com/community with a link to our socials and other things.

we need to do the following

 - [x] #444
 - [x] #443

**Comment by SinBin10** [comment]
Hello @kjaymiller can you please explain what is the feature that you want in a little more detail, as I can already see the social media links in the footer section of the about us page, just above the code of conduct.

**Comment by kjaymiller** [comment]
I'm sorry this actually is a simpler issue which I'm happy for you to address... 

We have some new social media locations that need to be change.

We have https://blackpythondevs.com/community with a link to our socials and other things. 

- we need to do the following

- [ ] Add a section about Instagram to the community page (@blackpythondevs)
- [ ] Update the LinkedIn Section to include our linkedIn Page (https://www.linkedin.com/company/black-python-devs)
