### ISSUE TITLE
Sponsorship Images are not responsive on smaller screens

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#441]
The sponsorships are not constrainted to the container.... This needs to be updated.

![Sponsorships on the leadership summit page not constrained to the window](https://github.com/user-attachments/assets/277be97e-dbcd-4d5e-9483-62f7f72fb7cf)

**Comment by TimOsahenru** [comment]
Just confirming that this issue is related to this URL https://blackpythondevs.com/leadership-summit-2024/ when in mobile view/smaller screens. If that's the case please assign this to me so I can fix it. Thanks

**Comment by TimOsahenru** [comment]
Fixed. Please review https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/454. Thanks

**Comment by TimOsahenru** [comment]
![Image 2024-09-19 at 12 04 33 PM](https://github.com/user-attachments/assets/35d272ad-ff8b-4050-9b8a-e67bf04e22d4)
