### ISSUE TITLE
Create a Comment Action for Automated Conference Issues

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#442]
We need to implement a GitHub Action within the existing workflow located at `.github/workflows/conference.yml` that automatically adds a comment to issues created by this workflow. The comment should say:
`"Automated issue, no action is required."`

### Requirements:
- Ensure that the comment does not apply to other manually created issues and only triggered when the conference actions is ran.

**Comment by JohananOppongAmoateng** [comment]
@TimOsahenru can you assign me to this

**Comment by TimOsahenru** [comment]
Cc: @kjaymiller
