### ISSUE TITLE
Update the LinkedIn Section to include our linkedIn Page (https://www.linkedin.com/company/black-python-devs)

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#443]
Update the LinkedIn Section to include our linkedIn Page (https://www.linkedin.com/company/black-python-devs) 

> LinkedIn 
Join our [LinkedIn Group](https://www.linkedin.com/groups/14336241/) to connect with professionals in the field, participate in relevant discussions, and stay updated with job opportunities and industry trends.

Should say

> LinkedIn
>
> Follow our [LinkedIn Page](https://www.linkedin.com/company/black-python-devs) to learn more about all the things happening around the community!
> 
> Also, join our [LinkedIn Group](https://www.linkedin.com/groups/14336241/) to connect with professionals in the field, participate in relevant discussions, and stay updated with job opportunities and industry trends.

**Comment by bboyjamba** [comment]
I'll handle this.
