### ISSUE TITLE
Create Dedicated support page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#456]
Currently we only have the donate page on the website.

I would like to add a donate page that includes:

- The commitchange embed (take the code from the homepage)
- An embed of our PITCH DECK

```html
<div
  style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;"
>
  <iframe
    loading="lazy"
    style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https://www.canva.com/design/DAGKXBERZ2s/AbT0GzW284THN6wSayNMMg/view?embed"
    allowfullscreen="allowfullscreen"
    allow="fullscreen"
  >
  </iframe>
</div>
<a
  href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGKXBERZ2s&#x2F;AbT0GzW284THN6wSayNMMg&#x2F;view?utm_content=DAGKXBERZ2s&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link"
  target="_blank"
  rel="noopener"
  >PITCH Deck</a
>
by Black Python Devs
```

- instructions for donation via PAYPAL, DAF, and CHECK,

```
  please email leadership@blackpythondevs.com for instructions.
```

**Comment by ronnzw** [comment]
Do you have a specific design that you have in mind?

**Comment by kjaymiller** [comment]
not really I think right now we need ANYTHING. 

More and anything get lots of questions at live events that not everyone knows how to answer off the top of their head.

**Comment by JohananOppongAmoateng** [comment]
@ronnzw @kjaymiller Are any of you working on this currently?

**Comment by kjaymiller** [comment]
@JohananOppongAmoateng  - I received your email. 

We prefer if people don't used the alternative issues to message us. 

The instructions can be found at - https://github.com/BlackPythonDevs/blackpythondevs/issues/127#issuecomment-2363782733 That said we prefer that those interested in using those methods email us first because we need to notify our bank provider of the incoming charge.

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller I made the changes please review

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  I think this issue should be closed since the pr has been merged
