### ISSUE TITLE
[REMOVE] Technical Manager Role from Leadership Page

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#463]
Our Technical Manager role have been [retired as of 16 Sept](https://github.com/BlackPythonDevs/blackpythondevs/blob/main/roles/leadership/retired-technical-manager.md)

The technical management role needs to be removed from the page.

**Comment by kjaymiller** [comment]
cc: @TimOsahenru  I'll make changes for #458

**Comment by Kabasitad** [comment]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/465

**Comment by Kabasitad** [comment]
removed the technical manager role

**Comment by TimOsahenru** [comment]
@Kabasitad Please read through this https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/CONTRIBUTING.md and mind you this issue has been resolved in this PR https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/458
