### ISSUE TITLE
Remove Technical manager from about page

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#469]
Following the recent updates to our roles, we would like to remove the Technical Manager position from our About page should reflect the leadership team structure in this page https://blackpythondevs.com/leadership/. More details -> https://github.com/BlackPythonDevs/blackpythondevs/blob/main/roles/leadership/retired-technical-manager.md

**Comment by kjaymiller** [comment]
@TimOsahenru - That is a good change. Can you also update this issue to also point to our full leadership page

**Comment by TimOsahenru** [comment]
> @TimOsahenru - That is a good change. Can you also update this issue to also point to our full leadership page

done
