### ISSUE TITLE
Update TalkPython Partnership

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#476]
Update the content of `TalkPython Training` in our `_data/partnerships.yaml` to now share our affiliate landing page which provides an easier workflow for those that want to support Black Python Devs while also learning.

New url: https://training.talkpython.fm/black-python-devs

**Comment by PartishtaP** [comment]
Hey @kjaymiller I would like to contribute
Assign me this issue
