### ISSUE TITLE
Update Maintainers and Contributors file for overassigning issues

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#477]
Hello @kjaymiller, I think we should include scenarios like this to our CONTRIBUTING/MAINTAINERS file. "... contributors should not be assigned to a new issue if they have an open PR still in review, except in scenarios where the issues are exclusively related to the existing PR", something like that

_Originally posted by @TimOsahenru in https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/470#issuecomment-2380576680_

**Comment by TimOsahenru** [comment]
I'll make a quick fix for this. Please assign it to me. Thanks

**Comment by TimOsahenru** [comment]
Please help close this Jay. Thanks

**Comment by kjaymiller** [comment]
Tim do you not have the ability to close it?

**Comment by kjaymiller** [comment]
@TimOsahenru  ☝🏾

**Comment by TimOsahenru** [comment]
I can now. Thanks
