### ISSUE TITLE
New Page additions

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#488]
Based on the initial PR of #487 We need to update our MAINTAINERS.MD with this information to make sure we provide it to contributors that need assistance.

When a new page is created there are things that should be included.

- If a new data type is created then we need a new file in `_data/`. JSON is preferred but YAML/CSV is also okay.
- Add the route to `tests/conftest` in the `ROUTES` constant.

https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/56e317bdd1228ee25ee0f801f928178e0590e29f/tests/conftest.py#L14-L21

**Comment by kjaymiller** [comment]
@BlackPythonDevs/documentation or @BlackPythonDevs/triage feel free to discuss

**Comment by cmm25** [comment]
kindly assign me this issue.

**Comment by dragid10** [comment]
> * If a new data type is created then we need a new file in `_data/`. JSON is preferred but YAML/CSV is also okay.

In what cases would YAML/CSV be accepted as opposed to JSON? If we can define when that scenario would happen, then I think that would reduce confusion for future contributors

**Comment by kjaymiller** [comment]
> > * If a new data type is created then we need a new file in `_data/`. JSON is preferred but YAML/CSV is also okay.
> 
> In what cases would YAML/CSV be accepted as opposed to JSON? If we can define when that scenario would happen, then I think that would reduce confusion for future contributors

I think CSV works if we had some data heavy information. I don't think we have anything like that now but I wouldn't want to have some information like annual sponsorship numbers or things in a JSON file (especially since it would be coming from a spreadsheet).

**Comment by JohananOppongAmoateng** [comment]
@cmm25 are you still working on this issue? Do you need help?

**Comment by cmm25** [comment]
Apologies I was held up this week but will push my branch tomorrow.

**Comment by cmm25** [comment]
Check pr #502. Note I discovered another error that I have explained concerning the ruby version that necessitated me to update it so please also review that
