### ISSUE TITLE
Update headers to be to follow accessibility guidelines in book-club.html

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#491]
https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/7bc8db1203900cc29555a87114c28820a8d65f41/book-club.html#L18-L23

Currently the h3 comes before the h2. These should be reversed.

**Comment by Brijeshthummar02** [comment]
@kjaymiller Sure i'll be changing it.

**Comment by Brijeshthummar02** [comment]
@kjaymiller i'm not able to locate the file, show me path.

**Comment by kjaymiller** [comment]
It's at the root of the project - book-club.html is the path.

**Comment by Brijeshthummar02** [comment]
@kjaymiller i tried all possible ways but unable to locate the file, could you please share the complete path.

**Comment by kjaymiller** [comment]
Have you pulled down changes to your local copy of the repo?

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  assign this to me

**Comment by kjaymiller** [comment]
@JohananOppongAmoateng - With someone already assigned this issue please do not begin working on tasks until they are assigned to you or offer help to the person in which the project has already been assigned.

**Comment by JohananOppongAmoateng** [comment]
Noted will keep that in mind

**Comment by JohananOppongAmoateng** [comment]
Noted thank you for letting me know
