### ISSUE TITLE
Pull request template for ensuring consistent PR formatting

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#499]
We need to add a Pull Request (PR) template to our repository to ensure that all contributors follow a consistent structure when submitting pull requests. This will help streamline the review process and ensure that all necessary information is included in each PR.

The template should include sections for describing changes, URL link to related issue, type of change, testing methods, and a checklist for the contributor(feel free to include any needed info)

## Implementation details
- Create a new file named PULL_REQUEST_TEMPLATE.md in the `.github/` directory.
- Add content to `PULL_REQUEST_TEMPLATE.md`

#### Description
Please include a summary of the changes and the related issue. 

#### Related Issue
Please link to the issue that this PR addresses.
Resolves: #<issue_number>

Note: to mark a box, replace `[ ]` with `[x]`.
#### Type of change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change
- [ ] Documentation update

#### How Has This Been Tested?
Describe the tests that were run to verify the changes.

#### Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

**Comment by JohananOppongAmoateng** [comment]
@TimOsahenru please can you assign this to me

**Comment by kjaymiller** [comment]
A PR came in for this already @JohananOppongAmoateng - Sorry about that.

They were cleared to work on it from our Office Hours held in the discord. 

I will mention to them that they should use the standard procedure of claiming a task before getting the work done.
