### ISSUE TITLE
Fix broken image in contributing.md file

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#500]
The file path for the broken image is incorrect, get the correct path to display the correct image
![image](https://github.com/user-attachments/assets/e48e55bb-1ee2-40ca-9f6a-af6b3bc50d21)

## Implementation details
Change the file path in the `CONTRIBUTING.md` file from `  ![Black Python Devs Codespace](/assets/images/BlackPythonDevs_codespace.png)` to `  ![Black Python Devs Codespace](/assets/images/blackpythondevs_codespace.png)` and be sure the image appears correctly

**Comment by GaurangMapuskar** [comment]
@TimOsahenru  I will pick it up
