### ISSUE TITLE
url in conferences will not replace invalid url

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#504]
When you pass in a url with an invalid protocol, the url is replaced but the protocol is not replaced.

```sh

```

============================================================================ FAILURES ============================================================================
**************\*\***************\_\_\_**************\*\*************** test_normalize_url[ftp://pycon.us] **************\*\***************\_\_\_**************\*\***************

test_url = 'ftp://pycon.us'

    @pytest.mark.parametrize("test_url", ["pycon.us", "https://pycon.us", "ftp://pycon.us"])
    def test_normalize_url(test_url: str):
        """
        Tests that urls are valid URLs with https:// protocols
        """

>       assert conferences.normalize_url(test_url) == "https://pycon.us"
>
> E AssertionError: assert 'https://ftp://pycon.us' == 'https://pycon.us'
> E
> E - https://pycon.us
> E + https://ftp://pycon.us
> E ? ++++++

tests/tests_conferences.py:12: AssertionError

```

```

**Comment by kjaymiller** [comment]
@dragid10 you were working on this. I wasn't sure if you wanted to look at it. This is coming after some refactors in #503

**Comment by dragid10** [comment]
Oooo interesting! I'm happy to take a look at it but if others want to get to it before me, then that's fine! I don't want to block anyone else from potentially taking this

**Comment by kjaymiller** [comment]
up for anyone

**Comment by dragid10** [comment]
Okay I actually thought of a solution because my brain was in the zone with this!
