### ISSUE TITLE
Make CFP date and link optional

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#518]
Currently the CFP link and date are required.

These should be optional especially when the CFP has expired.

![CFP and link are required](https://github.com/user-attachments/assets/40b6c1bf-69f1-427d-aedd-c9151d7c1831)

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller Good evening please can I get assigned to this. Thank you

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  it seems the issue templates dont support conditional logic so i am thinking about making the link and dealine optional
