### ISSUE TITLE
create a section for "Contributing" for the website with instructions from the README.

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#52]
I also think as things get a little more complex we can make them into that CONTRIBUTING.md file and link to it from the README

----

              I just organized the files for the README or the website. If we don't want public to production we can exclude in the `config.yml`

I think we can create a section for __Contributing__ for the website and reuse this images

_Originally posted by @oleksis in https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/49#issuecomment-1759930216_

**Comment by oleksis** [comment]
I will add the "CONTRIBUTING.md"
