### ISSUE TITLE
Fix typo in  CONTRIBUTING.md  :  "infracstructure"  to  " infrastructure"

### ISSUE THREAD

**Issue by Samuel-Njoroge** [BlackPythonDevs/blackpythondevs.github.io#525]
Typo in the second header 

" Diagram of infracstructure in use "

![typo](https://github.com/user-attachments/assets/8c8f890a-4341-4a57-ad41-951f69e1656e)

Preferably  to 

" Diagram of the infrastructure in use. "

**Comment by kjaymiller** [comment]
@Samuel-Njoroge would you be interested in resolving this issue?

**Comment by Samuel-Njoroge** [comment]
> @Samuel-Njoroge would you be interested in resolving this issue?

Yes. 

Working on it
