### ISSUE TITLE
[Blog Post] Create Recap Post for PyCon Uganda 2024

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#530]
Someone that was at PyCon Uganda please recap it for the blog.

Black Python Devs was represented at PyCon Uganda
We were proud to be a Sponsor (include sponsorship details)
Highlight any conversations or talks given specifically about Black Python Devs
Include some photos and links to other recaps that mention Black Python Devs

**Comment by TobiasHT5** [comment]
Can you assign this to me @kjaymiller

**Comment by TobiasHT5** [comment]
@kjaymiller I got a cyclic dependency while running bundle install. I'm really not familiar with ruby so I don't even know how to fix this. should I just first install eventmachine alone then re-run bundle install?

<img width="1002" alt="cyclic-dependency" src="https://github.com/user-attachments/assets/c08eb7b9-284f-4478-b721-096ff937fb6a">
