### ISSUE TITLE
Fix broken image in blog post

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#531]
This post has a broken image: https://blackpythondevs.com/2024-07-20-black-python-devs-partners-with-pyohio/. As seen in the file at https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/_posts/2024-07-20-black-python-devs-partners-with-pyohio.md?plain=1, there is a typo in the file extension—`-png` instead of `.png`. Please find the correct image file and update the extension to `.png`."

**Comment by kjaymiller** [comment]
@TimOsahenru  did you want to fix this?

**Comment by TimOsahenru** [comment]
Not immediately. Anyone with enough context can pick it up. Thanks

**Comment by mbvgua** [comment]
Hello, I've tracked down the issue, id like to work on it.

**Comment by mbvgua** [comment]
I think I have successfully resolved the issue, but I would like to add that it is getting harder to work on them since my codespaces are full. 

With this in mind, I would like to continue this conversation on issue #401
