### ISSUE TITLE
Include featured images to articles without images

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#533]
You can use this [image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/assets/images/bpd_stacked.png) as the featured image for any article without an image

**Comment by kjaymiller** [comment]
we should probably have a standard photo dimension that we use for the featured image that way when they are added to the carousel or on the top of the page they are not being strecthed.
