### ISSUE TITLE
Implement Standard Resizing for Featured Images in Blog Posts

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#538]
For better user experience ensure all featured images have a standard dimension.

#### Implementation
You can achieve this by either:
- Applying a standard size to all images globally across blog posts.
- Creating a specific CSS class for featured images, which can be applied on a per-post basis, depending on your preference.

For more details, refer to this [context](https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/533#issuecomment-2422315212).

**Comment by JohananOppongAmoateng** [comment]
@TimOsahenru can I get assigned to this

**Comment by JohananOppongAmoateng** [comment]
@TimOsahenru do you have a specific size you want the images resized to?

**Comment by TimOsahenru** [comment]
Maybe use same dimension as this image https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/gh-pages/assets/images/BPD_STACKED_featured.png or @kjaymiller what do you think ?

**Comment by kjaymiller** [comment]
I think it would be best if we found a reference on the internet that provides a suggestion so that we can make an educated decision.

**Comment by kjaymiller** [comment]
I also noticed in #543 that the ratio used is not a standard one. Which could have some rendering issues on devices...

Most devices would expect something like a 4:3 or 16:9 ratio. Instead the PR uses `524 : 933`.

I think we should use a ratio of 16:9 or 3:2 per instructions from https://tiny-img.com/blog/best-image-size-for-website/

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller it seems this issue needs to be closed or ?
