### ISSUE TITLE
How to we keep up with conferences that have already happened. They need to be removed from the site

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#54]
How do we keep up with events that have passed. We need to be able to quickly remove old events from the site.

I'm not sure with Jekyll

If the site moved to render-engine. There is a JSON parser I made a while back and we can create a filter that just doesn't include events before the current date.

**Comment by oleksis** [comment]
The Conferences collection will list issues tagged with "conference" and that have an "open" status y the final conference date is in effect. See example: [\[CONFERENCE\] DjangoCon Africa 2023](https://github.com/oleksis/blackpythondevs.com/issues/3)
