### ISSUE TITLE
Differentiate Font Sizes and Colors for Date and Description on Blog Page

### ISSUE THREAD

**Issue by Ngazetungue** [BlackPythonDevs/blackpythondevs.github.io#557]
Currently, the font sizes and colors for the date and description on the blog page are the same, which may impact the visual hierarchy and readability of the content. To improve the user experience, the font sizes and colors should be adjusted to create a clearer distinction between the date and the description text. Referring to this page: http://blackpythondevs.com/blog/

**Suggested Changes:**

**Date Font:**
- Reduce the font size slightly for the date, making it smaller than the description text.

**Description Font:**
- Maintain the current font size or make it slightly larger to ensure it stands out as the primary information.
<img width="993" alt="Screenshot 2024-11-04 at 10 50 26" src="https://github.com/user-attachments/assets/dab30fed-62ee-41e8-bf0a-52416b81a095">

**Comment by kjaymiller** [comment]
@Ngazetungue - thank you for taking this on! I think that is great

**Comment by Ngazetungue** [comment]
The PR is ready for review, find it here: https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/593
