### ISSUE TITLE
Include the following testcases

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#578]
Test 1:
Add a small post as a demo (in test as a test case and destroy it after)
Wait and let it rebuild and then check to see if the default image is grabbed.
 Test 2:
If you select the next_button you expect the image to change to a new one. Same for prev_button
 Test 3:
That slides match the links in the recent posts section
 Test 4:
When you click the links in the carousel they go to the corresponding webpages

**Comment by kjaymiller** [comment]
Time any chance that you were able to add all these tests?

**Comment by TimOsahenru** [comment]
> Time any chance that you were able to add all these tests?

Oops! I've added all except Test 1. I'll be on this right away. Thanks
