### ISSUE TITLE
user redirected to github issues

### ISSUE THREAD

**Issue by ankitgadling** [BlackPythonDevs/blackpythondevs.github.io#58]
user is redirected to the #9 if he clicks on the online-first in about us page
![blackpythondeveloper](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/86833325/d9070307-318f-411b-8d74-8f16e3e2373a)

**Comment by kjaymiller** [comment]
@ankitgadling - good catch... were you interested in contributing the fix?

**Comment by ankitgadling** [comment]
yes @kjaymiller I am interested in contributing the fix could you please assign this issue to me
