### ISSUE TITLE
Only show the blog posts that are in recent posts. This also means that we can de-emphasize that section and make it smaller.

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#580]
![Markup Changes to the Latest Posts Section](https://github.com/user-attachments/assets/e58c33b5-a127-48a4-9490-c2bc7684469b)

**Comment by TimOsahenru** [comment]
@kjaymiller this commit https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/592/commits/ead557e1f7a0d206c173790d0c3e6656bd2cd806 addresses this issue

**Comment by kjaymiller** [comment]
I noticed
