### ISSUE TITLE
Overhaul the Leadership Section with the announcement of a new Leadership Model

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#596]
![Leadership Section](https://github.com/user-attachments/assets/d3f600f5-d3ee-490c-ba00-700851079427)

**Comment by TimOsahenru** [comment]
Hello @kjaymiller, could we add more details to this? What the announcement entails, the names of the new leaders if applicable. Thanks

**Comment by kjaymiller** [comment]
FMI : https://github.com/BlackPythonDevs/blackpythondevs/discussions/137

**Comment by TimOsahenru** [comment]
something like this, right ? 
![image](https://github.com/user-attachments/assets/b403d769-d302-4613-889d-fec658081e87)

**Comment by kjaymiller** [comment]
yup...

Whats going on with the images.. I've noticed they stretch weird. Different issue.

**Comment by TimOsahenru** [comment]
> yup...
> 
> Whats going on with the images.. I've noticed they stretch weird. Different issue.

They are? I really can't see what you're pointing at
