### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by oleksis** [BlackPythonDevs/blackpythondevs.github.io#6]
Contributing to Black Python Developers website

**Comment by kjaymiller** [comment]
we can include the instructions for making a contribution

## For Contributions
- File an issue or Claim an existing one
- Have the issue assigned to you (leave a comment)
- Fork the code and make the changes on your own branch 
- Submit a PR

Contributing needs to include all of the tools needed:
- pre-commit

**Comment by oleksis** [comment]
Member can use Devcontainers or Codespaces. I will update the `devcontainer.json` with `pre-commit`

**Comment by kjaymiller** [comment]
Add playwright and local serving steps #21
