### ISSUE TITLE
Update About.html

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#9]
Update the about page with the following text.

---
## What is Black Python Devs

Black Python Devs is an [online-first](#why-online-first) community for python developers of all skill levels that identify as black.

Our goal is to:
1. Show the vast community of black Python developers that exist but whose voices are often not amplified in the community.
2. Support black Python developers in their careers by highlighting their expertise and creating mentorship opportunities.
3. Learn from those who are creating and organizing events and other groups with communities of black developers. 

## Why online first

We hope in the long run to create many in-person user groups and events, but we have to understand where we can make the largest impacts.

To do this we're hoping to gather folks from around the world and see where our largest audiences are.

---

**Comment by shaswat-satyam** [comment]
Hey @kjaymiller! Can you assign me the issue? Do we have to make a new about.html or update About.md?

**Comment by kjaymiller** [comment]
Update the existing one
